### ISSUE TITLE
Issue right after installation

### ISSUE THREAD

**Issue by riker09** [witrin/TypoGento#23]
First off, I have absolutely no knowledge of Typo3, so if I'm doing something really, really stupid here please be kind.

I tried getting TypoGento to work but it seems it isn't mainained anymore (correct me if I'm wrong). I managed to cover most of the backend stuff, I'm only having trouble with points 5 ("Add the scheduled task for clearing the Magento API cache in Admin Tools > Scheduler") and 6 ("Setup the TypoGento routing system"). When I went back to check on the frontend I recieved a error 500. Examining the log files I could come up with

```
mod_fcgid: stderr: PHP Fatal error:  Call to undefined method t3lib_div::GPvar() in
/path/to/typo3/docroot/typo3conf/ext/fb_magento/lib/class.tx_fbmagento_hookobserver.php on line 33
```

I googled this error on the internet and found this page: http://bugs.typo3.org/view.php?id=18358 I took a shot in the dark an switched from `t3lib_div::GPvar()` to `t3lib_div::_GP`, which seemes to do the trick for me.

**Comment by witrin** [comment]
I can not speak for Flagbit here, regarding to your question if TypoGento is still maintained; but the last update is apparently several months old.

With the error you have posted here, I'm pretty sure, that you use the original sources from Flagbit (`tx_fbmagento`). I've improved many parts of it, with this fork (`tx_typogento`); and thus all documentation relates to it. If you want to give it a try, you have first to uninstall the package from Flagbit (`tx_fbmagento` and `Flagbit_Typo3connect`). After that just follow the instructions in the [README](https://github.com/witrin/TypoGento/blob/develop/README.md) and checkout the [Wiki](https://github.com/witrin/TypoGento/wiki/Configuration) for the last step on TYPO3.

**Comment by riker09** [comment]
Okay, it seems like I downloaded the wrong package by mistake. Got your version running so far. But I'm still puzzled with how to display a Magento page within Typo3.

**Comment by witrin** [comment]
This is no problem at all! But would you please open a new ticket for your next question, and formulate it more precisely.
