### ISSUE TITLE
How to display a product on a Typo3 page

### ISSUE THREAD

**Issue by riker09** [witrin/TypoGento#24]
I'm facing the problem that my client wants to display products on his Typo3 powered website using Magento as eCommerce software. TypoGento to the rescue. But I have almost no knowledge of Typo3, I'm just beginning to learn. So I got the plugin up and running so far but with the given documentation it is very difficult for me to display products or categories on a Typo3 page. Is there an example available I'm missing?

**Comment by witrin** [comment]
How about the Gists for the [common setup](https://gist.github.com/3220616) and the [basic routes](https://gist.github.com/3220650) in the [Wiki](https://github.com/witrin/TypoGento/wiki/Configuration)! Therewith you should be able to display Magento products on TYPO3 pages easily by setting up the TypoGento plugin through the TYPO3 backend.

**Comment by riker09** [comment]
Please ignore my last comment, I was able to get it working. My mistake was that I thought I had to mess around with some more TypoScript but the plugin made some nice additions to the Typo3 backend instead. Maybe it is helpful to show a screenshot of the backend at this point?
