### ISSUE TITLE
How to display navigation on category page

### ISSUE THREAD

**Issue by riker09** [witrin/TypoGento#25]
How can I display a vertical navigation on a page? Or in other words, how can I load any Magento block within a Typo3 page. I'd like to see a code snippet, please and hopefully I can work my way up from there.

Oh, by the way, thank you for improving TypoGento. It is really sad that the original plugin isn't maintained anymore. I really appreciate your work and what's more, your help.

**Comment by witrin** [comment]
There is an example in the [README](https://github.com/witrin/TypoGento#usage) for the Magento block `top.search`. It is only possible in TypoScript Setup, which means you have to find a way to put `temp.search` into your TYPO3 Template. Check out the reference of `plugin.tx_typogento_pi1` in the [Wiki](https://github.com/witrin/TypoGento/wiki/Configuration) for more properties:

``` text
temp.search < plugin.tx_typogento_pi1
temp.search {
     # Render Magento block 'top.search'
    block = top.search
}
```

Please excuse my late response. Currently I've serious issues with my back.
