### ISSUE TITLE
How to change store view

### ISSUE THREAD

**Issue by riker09** [witrin/TypoGento#26]
Sorry if I'm keeping you busy with what might be simple stuff for somebody with a lot more experience. But I'm willing to listen, read and learn. Can you please explain how to change the store view that gets used for the display of category or product pages?

My setup: I've installed a brand new Magento store and a Typo3 website. I've create a couple categories and a single simple product. I've created a second store view in Magento and named it "Typo3". In the Design settings I've changed the theme to "blank". How can I tell the TypoGento plugin to use this second storeview whenever a category or product page is displayed in Typo3?

**Comment by witrin** [comment]
The Magento store view is bound to the TYPO3 frontend language or, if not set, to the deprecated property `tx_typogento_pi1.storeName`. See also in the [code](https://github.com/witrin/TypoGento/blob/develop/src/TYPO3/typo3conf/ext/typogento/lib/class.tx_typogento_div.php#L221) and the [how-to](http://www.typogento.com/documentation/how-to-install-typogento.html). I'll refactor the TypoScript interface soon, I also forgot to document this in the [Wiki](https://github.com/witrin/TypoGento/wiki/Configuration).
