### ISSUE TITLE
Categories are not updated to the Back-End Plugin

### ISSUE THREAD

**Issue by Smucks** [witrin/TypoGento#27]
It seems that the Categories are not updated to the BackEnd Plugin after the first install.

I tried to add root-Categories AND Sub-Categories, but booth are not visible in the Magento Extension Plugin.
- Deleting the typo3temp folder did not work it out.
- Clearing the Typo3 cache changed nothing.
- Deleting the Magento cashe did not help.
- ReBuild the Magento Indexes did not solve the problem.

All categories are places under the default categorie.

What to do? If you could explain me how and where the Data is fetched i could take a look over it. :)

**Comment by Smucks** [comment]
It seems that there is a loop in which the categories are listet, and as if this loop only runs one time for each lvl.

**Comment by witrin** [comment]
That's absolutely right! The bug is [here](https://github.com/witrin/TypoGento/blob/develop/src/TYPO3/typo3conf/ext/typogento/lib/class.tx_typogento_tcafields.php#L213-219) and should be herewith replaced:

``` php

    if (is_array($value['children'])) {
        foreach ($value['children'] as $child) {
            $walk($child);
        }
    }
```

The bug fix will be published soon. Thank you very much for the report!

**Comment by Smucks** [comment]
Work´s like a charm. :)

**Comment by witrin** [comment]
Glad to hear it!
