### ISSUE TITLE
Categories, Products and Subcategories.

### ISSUE THREAD

**Issue by Smucks** [witrin/TypoGento#29]
With a structure like this:
- Default Category
- \- Products
- \- - First Category
- \- - Second Category

and some Products in each of the Categories, and 2 Typo3 Sites, each with a Plugin "Category" in it Products will be rendered the following way:
1. If a product is in "First Category" it is shown correct in Page 1.
2. If a product is in "Second Category" it will not be shown in Page 2, unless you put it in the Category Products too. Good Thing: It is not shown in Page 1.

Maybe something with the old loop?

**Comment by witrin** [comment]
Did you also checked the behaviour on the original Magento frontend? The TypoGento plugin renders just the Magento block `content`, which outputs the products.  Maybe this is a weird bug on Magento side?

**Comment by Smucks** [comment]
I´ll have a look monday. Enjoy your Weekend! :)

**Comment by Smucks** [comment]
Weird. When you have unused Plugins, "not referenced Plugins", in the Page, this failure happens. Has to do something with TemplaVoila ...

-Closed-
