### ISSUE TITLE
static blocks in different languages

### ISSUE THREAD

**Issue by denyo256** [witrin/TypoGento#32]
I'm trying to include the top-links from Magento on every page with the following typoscript:

```
lib.shopheader < plugin.tx_typogento_pi1
lib.shopheader {
  block = top.links
}
```

This works fine in all languages as long as there is a Magento content element. On any other page, only the default language with the default store view is working, all other languages result in an error "Page not found". 

Do you know any solutions for this?

**Comment by witrin** [comment]
Did you setup a default route respectively which setup did you use (`config.tx_typogento.routes`)? The latest Gist revision is unfortunately not free of bugs. The thing is, as long there is no content plugin, which sets the Magento action, you'll need a default Magento action like 'core/index/index' which should be rendered. Otherwise Typogento detects no response and throws the 404.

In addition, I am very sad that I can not publish the latest version of Typogento that supports beside Extbase and namespaces also a one-click setup, since I still lack the synchronization and authentication of accounts, and I can not find time to finish this off.

**Comment by denyo256** [comment]
I used the routes from your latest Gist.
What makes me wonder is the fact that it works well as long as I don't use an alternative language.

**Comment by witrin** [comment]
You mean that your described problem (404) doesn't appear as long as you don't use an alternative language?

**Comment by denyo256** [comment]
Yes, the top-links appear in my default language on every page, even on those pages without a Magento content element. But switching to an alternative language results in an 404 error.

**Comment by witrin** [comment]
Please add `echo 'Dispatch URL: ' . $this->_url;` right after [this](https://github.com/witrin/TypoGento/blob/develop/src/TYPO3/typo3conf/ext/typogento/lib/class.tx_typogento_interface.php#L25) line and post its output for a page, without a Magento content plugin, in the default language and in a non default language; maybe you have to disable the default error handler for this.

**Comment by denyo256** [comment]
Output for default language:  <code>Dispatch URL: /cms/index/index/index/? </code>
Output for alternative language:  <code>Dispatch URL: /cms/index/index/index/? </code>

**Comment by witrin** [comment]
I assume on both pages were no Magento content plugins and the first output went well! Did you setup the store view for the alternative language in the backend or with `plugin.tx_typogento_pi1.storeName`?

You see also that the latest Gist, you use for the dispatch, is unfortunately not correct. It should be `/cms/index/index` in the default case.

**Comment by denyo256** [comment]
Exactly, there were no Magento content plugins and the first output went well. 
I set up store views for all alternative languages with <code>plugin.tx_typogento_pi1.storeName</code>. 

I tried to correct my dispatch for testing, but unfortunately I wasn't successful.

**Comment by witrin** [comment]
You could try to comment out `plugin.tx_typogento_pi1.storeName` for the alternative languages to exclude that it's responsible for the 404. If this was the problem, you could try to setup the store name by using the backend; there is a dropdown within the language records to do that. Have you made any other settings of TypoGento for the alternative languages?

**Comment by denyo256** [comment]
The dropdowns within the language records have all been set, so commenting out <code>plugin.tx_typogento_pi1.storeName</code> has no effect. If I set the dropdown to the default store view, the 404 is gone, but the Magento output is in default language (of course).
No other TypoGento settings for the alternative languages have been made, only the storeName.

**Comment by witrin** [comment]
You don't need to set both, using language records only is enough. Did you test the other languages in the default Magento frontend respective is there a home page set for the other store views?

**Comment by denyo256** [comment]
I tested them in the Magento frontend, but didn't have a homepage set. I now set the homepage for all store views and the 404 is gone. Great!
Thank you very much for your help.

**Comment by witrin** [comment]
You're welcome!
