### ISSUE TITLE
Dispatch different store views

### ISSUE THREAD

**Issue by denyo256** [witrin/TypoGento#36]
Hi, 

I'm actually trying to upgrade my old TypoGento shop to Typo3 6.2 and Magento 1.9 with your reworked extensions. So far, it is working pretty well, just one thing is giving me a headache. 
Is it possible to switch between different store views? And could you give me a hint what to do?

Best regards,
Dan

**Comment by witrin** [comment]
Yes this should be possible through the routing. Unfortunately I'm not able to support this extensions any longer but I'm too busy to update the README.

**Comment by denyo256** [comment]
Sad to hear that you don't support these extensions anymore. At least I was able to switch between my different store views, I just used some wrong typoscript settings.
