### ISSUE TITLE
Extension installation error

### ISSUE THREAD

**Issue by vetmode** [witrin/TypoGento#4]
After installing the TYPO3 module in extension manager:

```
Catchable fatal error: Argument 4 passed to t3lib_cache_Factory::create() must be an array, null given,
called in C:\xampp\htdocs\typo3\typo3conf\temp_CACHED_ps7c6a_ext_localconf.php on line 1562 
and defined in C:\xampp\htdocs\typo3\t3lib\cache\class.t3lib_cache_factory.php on line 82
```

**Comment by witrin** [comment]
This is caused by [c3a0027](/witrin/TypoGento/blob/c3a00273a132f10970bd4186fee44340dc464f14/src/TYPO3/typo3conf/ext/wee_typogento/ext_localconf.php#L111-116), and its unclean use of global variables. I will fix this within the next hours.

**Comment by witrin** [comment]
I think I will remove this part. The [caching framework garbage collection task](http://wiki.typo3.org/Caching_framework#Garbage_collection_task_2) should be used instead to clean up the cache, which currently is only used for SOAP requests both in backend and in frontend.

**Comment by vetmode** [comment]
Confirmed fixed, thanks witrin.

**Comment by witrin** [comment]
My pleasure. Thanks for reporting this bug.
