### ISSUE TITLE
No form to set Magento group membership

### ISSUE THREAD

**Issue by vetmode** [witrin/TypoGento#5]
Upon installing and configuring the TYPO3 extension I got:

```
Access denied 
Magento group membership was not set.
```

I don't think I saw a form to declare this. Fixed it by setting it manually in `be_user.tx_weetypogento_group`.

**Edit:** Is this supposed to be set in the Magento module under `TYPO3 Frontend > Users Group`? I just tried it this way but that didn't change anything in `be_user.tx_weetypogento_group` in the TYPO3 database.

**Comment by witrin** [comment]
The desired form can be found under the tab "extended" on the edit page of the appropriate TYPO3 backend user. I had tried briefly in the [quick installation guide](/witrin/TypoGento/wiki/Installation) to describe this:

> Setup the Magento role for the TYPO3 backend accounts in `Edit > Extended > Magento Role`

As far as I know, there is currently no possibility in Magento CE that a user gets assigned several roles. So the corresponding role has to be assigned separatly to each TYPO3 backend user. 

Perhaps you could provide more understandable texts for this purpose (related #2). I'm unfortunately not talented for that matter.

**Comment by vetmode** [comment]
Sure I'll write you a guide once my installation is up and running.
