### ISSUE TITLE
Error when trying to open Magento Admin in TYPO3

### ISSUE THREAD

**Issue by vetmode** [witrin/TypoGento#7]
Using the newest developer release:

```
Fatal error: Class 'tx_weetypogento_magentoHelper' not found in 
C:\xampp\htdocs\typo3\t3lib\class.t3lib_div.php on line 4934
```

**Comment by witrin** [comment]
The class `tx_weetypogento_magentoHelper` should be resolved by the autoloader, which uses [`ext_autoload.php`](/witrin/TypoGento/blob/c31ebb4747703d3c4b7396a0e69898f154cb25ff/src/TYPO3/typo3conf/ext/wee_typogento/ext_autoload.php). Unfortunately I can't reproduce this error. Make sure the TYPO3 cache is completely cleared, and if this not helps, I will need the whole stack trace from you, if possible.

**Comment by vetmode** [comment]
You are correct, clearing the "typo3temp" folder did the trick. Thanks Artus.
